# Gameplay features
allow_fullscreen: n
enable_ai: y
enable_player_ai: y
show_unconstructable_products: n
show_help: y

# Graphics
fov_deg: 50
sdf_text: n
sdf_icons: n
skip_postprocessing: y
fps_cap: -1
v_sync: n

# Debug info
show_fps: n
draw_renderrects: n
draw_textrects: n
suppress_datanode_warnings: y
show_preformance_stats: n

# Gameplay variables
base_tech_progress: 10
tech_progress_per_lab: 10

#default_savefile: year_2
default_savefile: industry