# Gameplay features
enable_ai: y

# UI config
allow_fullscreen: n
enable_player_ai: y
show_unconstructable_products: n
show_help: y
make_ui_panels_exclusive: y
transferplan_draw_second_solution: n

# Graphics
fov_deg: 50
sdf_text: n
sdf_icons: n
skip_postprocessing: y
fps_cap: 60
v_sync: y
camera_rotation_sensitivity: 0.01  # rad/px

# Debug info
show_fps: n
draw_renderrects: n
draw_textrects: n
suppress_datanode_warnings: y
show_preformance_stats: n

# Gameplay variables
base_tech_progress: 10
tech_progress_per_lab: 10

#default_savefile: year_2
default_savefile: industry